--- 
- hosts: utat
  become: no
  gather_facts: yes
  vars_prompt:
    - name: export_loc
      prompt: Location of Slack export
      private: no
  vars:
    - dockerfile_loc: "{{ ansible_env.HOME }}/dockerfiles" 
  tasks:
    - name: Copy export
      copy:
        src: "{{ export_loc }}"
        dest: "{{ dockerfile_loc }}/slack-export-viewer/exports"

    - name: Restart container
      community.docker.docker_container:
        name: slack-export-viewer 
        state: started
        restart: true
