--- 
- hosts: utat
  become: no
  gather_facts: yes
  vars_prompt:
  vars:
    - dockerfile_loc: "{{ ansible_env.HOME }}/dockerfiles" 
  tasks:
    - name: Copy Docker files
      copy:
        src: files/slack-export-viewer
        dest: "{{ dockerfile_loc }}"

    - name: Build docker container
      community.docker.docker_image:
        name: slack-export-viewer
        build:
          path: "{{ dockerfile_loc }}/slack-export-viewer/"
        source: build

    - name: Message user
      debug:
        msg:
          - "Please modify the docker-compose file for your specific configuration"
          - "Then, bring the compose file up before adding"
